include:
   docker run --name docker -p 80:80 -d fsorge/dockerun:latest

version: '3.8'
  services:
     docker:
image: 'fsorge/dockerun:latest'
  container_name: 'docker'
  ports:
   - 80:80

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -f path/to/Dockerfile .
